[package]
name = "tokenxllm"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"
# Add if using OpenZeppelin for ERC20:
# openzeppelin = { version = "0.1.0", features = ["contract"] }

[[target.starknet-contract]]
sierra = true
casm = true